name: Build Packer Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-packer-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Validate Packer Template
        run: packer validate packer.pkr.hcl

      - name: Build Packer Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: packer build packer.pkr.hcl
